public class Test{
	public static void main(String[] args){
		//Note: each row is 302 char long. 
	String map = 
"                                                                                                   MMMMMMMMMMMMM                                                                                                                                                                                            \r\n" +
"                                                                                                MMM             MM   MM                                                                                                                                                                                     \r\n" +
"                                                                                              MMM              MMMMMMMMM                                                                                              MMMMMMM                                                                               \r\n" +
"                                                                                         MMMM                        MM                                                                                          MMMMM       MMMM                                                                           \r\n" +
"                                                                                       MMM                           M                                                                                          MMM             M                                                                           \r\n" +
"                                                                                   MMMM                             M                                                                                        MMM               MMMMMMMMM MMMMM     MMMMMMMMM                                                \r\n" +
"                                                                   MM              MM                               M                                                                                       M                 M         M    MM  MMMM       M   MM                                          \r\n" +
"                                                                  M  M            MM                                 M                                                                             M        M                           MM    MMMM          MMMMMMMMMMMMMMMMMMMM                            \r\n" +
"              MMMMMMM                                            M  MM          MM                                   M                                                                             M MMM   MM                            M                   MM                MMM                          \r\n" +
"         MMMMMM    MMMM                   M                     MMM MM           MMM  MM                             M                                                                            M   MMMM  M                            M                  MM                    MMM                       \r\n" +
"         M                MMMMMMMMMMMMMMMM MMM                 M    MM              MM .M                           MM                                                                            M   M M MMM                           MM                MM                         MM                     \r\n" +
"       MMM                M                     M             MM     MMM MM    .........  M                        M                                                                              M   MMM                                M                MM                            MMM                 \r\n" +
"      MM                  M                      MM MMMM    MMM        MMMMM...      . .   M                       MM                                       MM MM                             MMM MM   MMMM                         MMMMMM                 MM                       M     M                 \r\n" +
"     MM                  MM                                               MM       .   .   MM                    MMMM                                    M       MMMMMMMMMM            MMMMMMM   MMMM    MMMMM                     MM                        MM                   MM MMM  M                 \r\n" +
"     MM                  MM                                               MM     ..   .     M                   MMM                                 MM MMM        M        MMM MMM  MMMM            M    MM MM                      M                   M    MM                    MM  MMMM                 \r\n" +
"       MMM               MM                                           MMM      ..    ..     MM               MMM.                                  MM            M           M MM MM                M  MMM  MM                       MM              MM   MMMM                       M                      \r\n" +
"   MMMM M                MM                                         MM       ..     ..       M              MMMM...                               MM              M  MMMMMMMMM MMM                  M MMM    MM                       MM            MM                             MM                       \r\n" +
"   M   M                 MM                                        MM       ..      .        M         M MMMM    ...                             MM               M   MM MMMM M                    M           M                       M            M                      MM     MM                        \r\n" +
" ...MM                      MMMMMMMMMMMMMMMMMMMMMMMMMMMMM        MM       ..        .        M        MM           ...            MM            M                 M     MMM  M                    MM            M                      M      MMMMMM                   MMMMM    MM                          \r\n" +
"...M                         M                         MMMM     MM      ..     MMMMMM        M        M              ...MMM    MMMMMM          MM                 M     MMM                       M             M                      MM   MM     M                  MMM MM  MMM...........................\r\n" +
"    MMMMM    MMM   MMM        M                        MM  MM  M      ..      MM   MM        M        M               MM   MM        MM      MM            MM     M                                M            MM                      M  MM      M         MMMMMMMMMMM MM  MM.............................\r\n" +
"     MMM   MM   MMM   MMM     M                        MM    MMM     .        M      M  MMM  MM      MM                MM              M   MM            MM MM    MM                               M              M                     MMM        M         MM          MM   M                             \r\n" +
"     MM  MMM             MM   M                        MM     M    ..       MM       M  MMM   MM     M                MMM             MM  MM             M  M      M                               M               MM                  MM          M        MM           M    MM                            \r\n" +
"    MM MM                  M   MM                      M       MMMM          M       MMM  M      MMMMM                  MM          MM   M             MM  M      M                                M               MM                   M          M        MM           M     M                            \r\n" +
"     MM                    M    M                      M       M M           M            MM                             MM      MMM     M              MM M    MMM                                M                M                   M          MMM     MMMMM         MM    M                            \r\n" +
"                            MM MM                      M          MMM        M              MM                           MMMMMMMMM ...    M              M  MMMM MM                                M                 M                  M             M         MMM       M   MM                            \r\n" +
"                              M                       MM             MMMM  M                 MM                                ..    ....  M             M    MMM                                  M                 M            MM MM M              MMMMM      M         M MM                            \r\n" +
"                              M                       MM                M  M                  MM                      MMMMMM  ...        ...M           M     MM                                   MM                M           M    MM               MMM MM      M        MMMM                            \r\n" +
"                               MM                     MM                M M                     M                     M   MM  ..      .......MMMMM     MM    MMM                                    MM             MM          MM                            MM    MM                                       \r\n" +
"                               MM                     M                 MMM                     M                   MM   MMM  ..........   ..    MM    M     MM                                      M             MM          M                      MMM     M    MM       MMM   MM                        \r\n" +
"                                 M                    M                  MM                 MMMM                      M    M .......       ..      MMMM    MM                                        M              M MM       MM                   M   MM    M      M      MM      M                       \r\n" +
"                                 M                    M                  M             M  MMM                        M     MM  ..          .. MM        MM   MM                                      M                MM       MM                  MM    MM   MM     M       MM   MMM                       \r\n" +
"                                  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM  MMM    M            MMMMM                           M   MMMM   ..        .. MM MM  MMM       M                                    MMM                 M      MM                  M      MM  M      M       MM   MM                        \r\n" +
"                                 M                          M   M   M    M              MM                             M     M    ...      .. MM   MM          MM                             MMMMMM   MM                 M     MM               MMMM       MMMM     M      M MMMM                          \r\n" +
"                                 M                          M  MMMMMM    M         MMMM MM                         MM  M      M      ..    .. MM                MM                         MMMMMM        M                 M      MMMMMMMMMMMMMMMMMM          M     MM      MMM M                           \r\n" +
"                                 M                          M     MMMMMM MMMMM   MMM MM MMMM                      M   MM MM   MM      ... ...M                  MM                      MM                MM               M      M                          MM     MM..     MM  MM                         \r\n" +
"                                M                           M    M MMMMM   MMMM      MMM  M                    M       M MM    MM       ....M                   MM                      M                    MM          MM MMMM  MM                            MM MM  ..   MM     M                        \r\n" +
"                                M                           M   MM MMMM  MMM         MMM M                     M     MMMMMM     M          MM                   MM                     MM                      MMMMMMM  MM     MM  M                             MMMM    ..  MM    M                        \r\n" +
"                               MM                           M     M   MM            M M MM                      MM    MMMM       MMM     MM                     MM                     M                             M  M       MM M                              M       ... M    M                        \r\n" +
"                               MM                           M                     MM   MM                      MM     M M         MM    MM                      MM                     MM                            MM M        MMM                             MM.........MMM    M                        \r\n" +
"                               MM                           M                     MM                           M   MMM  MMM       MM   MM                       MM                      MM                            MM           M                            MM..........MM      M                       \r\n" +
"                               MM                      MMMMMM                    M                                     MMM MMMMMMM     M                       MM                         M                           MM            M                       M   MM         M        MM                      \r\n" +
"                               MM                      MM                      MM                                     MM MMMMM      MMMMM                     M MM                       MMMMM                        MM             MM                    MMM   MMM       M      MM                        \r\n" +
"                                M                     M                       M                                              M      M    M          MMMMM   MM   MM                     M - M                         MM              MM                 MM  MM M  MM    MM    MMM                          \r\n" +
"                                 M                  MM                        MM                                             MMMMMMM      M        M    M   M     M                    MM- -M                        MM                 MMM               MM    MMM MM  M      MM                           \r\n" +
"                                 M  MMMMMMMMM       M                         M                                            MMMM            MMMMMM      MM  MM     M        MMMMMM       MM- -MMM                  MMM                      MMMMMMMMMMMM     MMMM  MM    M   MMM                             \r\n" +
"                                 MMM         M     M                       MM                                              MM              MM                      M M MM  M  M          M - -MM                   M                                      MMMM         M  MMM                               \r\n" +
"                                  MM          MM  MM                     MMM                                                MM             MM                      MMMM MM M  M           MM - MM                  MM                                        MM       M  MM                                 \r\n" +
"                                    M           MMM                      MM                                                   M            MM                      MM - - - -  MM          MM -MM                  MM                                          M       MMMM                                 \r\n" +
"                                    MM           MM      MMMM  MMMM  M  MM                                                     M           MM                      MM- - - - - MMM         MM- -MM                   MMM                                        M       MMM                                 \r\n" +
"                                    MM             M  MMMM   M      M M  MM                                                    M           MM                      M  - - - - - - MM      MM- - MM            MMM  MMM  MMM                                    MM                                           \r\n" +
"                                     MM             MMM              MM  MM                                           MMMMMMMM         MMMMMMM     MMMM           MMM  MMMMMMMM- - -M   MM MM- - MMM MM    MMM    MM     MM                                     MM                                          \r\n" +
"                                       M            MM                MM MM                                          MM  MMM          MM     MM     MMMMM        MM MMMM      MMMMMMMMMMM   MMMMMM    MM  MM             MM                                     MM                                          \r\n" +
"                                       M            MM                MMM                                             M              MM        MM     MM M      MM                                      MMM              MM                                     MM                                          \r\n" +
"                                       MM           MM                                                                MM             MM         MM     MMM      MM                                      MM               MM                                      M                                          \r\n" +
"                                        M          M    MM MM                                                         MM             MM          MM  MMMMMM  MM  M                                      MM                 MM                                   MM                                          \r\n" +
"                                        MMM         MMM    MM                                                         MM              M           MM  M   MM   M MM                                      M                   M MMMMM                             M                                          \r\n" +
"                                          MMM             MM                                                          MM             MM        MMMM MM     M   M  M                                       M                     MMMMMMMMMM                      MM                                          \r\n" +
"                                            MMMMM        MM                                                           M             MM         MM  M        M  M   MMMMMMM MMMM                           MMM                           MMMMM                  MMM                                          \r\n" +
"                                                 MM      M                                                            MMM           M         MMMMM         MMMM         MM   M                            M                              M MM      M          M                                            \r\n" +
"                                                   MM     MM                                                             MMMMMM  MMM      MMM      MM       ...               M                             M                            M    MMMMMM  M      MM                                             \r\n" +
"                                                    MM   MM                                                                    MMMMMMMMMMM          MM      ...               M                MMMM         M                          MMM             MMM MM                                               \r\n" +
"                                                      M  M         MMMMMMMMMMMM                                                MM  MM                MM     ...   MMMMMM      M               MM MM         MMMM                        M             MMMMMM                                                \r\n" +
"                                                     MMMM        MM           MMMM                                             MM                    MM MMMMMMMMMM      MMM   M                 M MM  M  MMM    MM                   MMM              M                                                     \r\n" +
"                                                      M  MMM   MMM               MM                                           MM                    MM                    MMMMM                 MM MMMMMMM      MMMM                 MMM              MM                                                    \r\n" +
"                                                      MMMMM MMM                    MMM                                        M                     MM                        M                  MM               MMM MM          MMM   M              MM                                                   \r\n" +
"                                                          MM                          MMMMM                                  M                     MM                       MMMMM                  MMMMMMM            MM         MMM    MM               M                                                  \r\n" +
"                                                            M                              MMM                               M                     MM                       MMMMM                        MM           MM          M      MMM              MM                                                \r\n" +
"                                                          MM                  MMMM          MMMM                            MM                      MM                        M  M                        M           MM        MM          M             MM                                                \r\n" +
"                                                          MM                MM   M        MMM MM                           MM                       MM                        MM MM                       M           M         MM          MM             MM                                               \r\n" +
"                                                         MM               MM      MMMMMM      MM                           M                        MMM                        MM MM                      M           M          M            MM   MM       M                                               \r\n" +
"                                                        MMMM           MMM                   MM MMMMMM                   MM                              MMMMMMM              MMM   M                    MM           MMM      MM               M  MM M     M                                               \r\n" +
"                                                       MM  MMMM       MM                      MM     MMMMMMM              M                                    M          MMMM  MMM  MM                 MM              M      MM               M  MMMMM    M                                               \r\n" +
"                                                      MM          MM M                                      MM            M                                     MMMMMMMMMM        MM   MMM             MM               M      MM                M  MM MM MM                                                \r\n" +
"                                                      MMM          MMM                                       MMMMM        MM                                      MMM             MM   ..M             MM               MM    MMM                MM  MM  MMM                                                \r\n" +
"                                                       MM             MM                                         M .......MM                                       MM              MM ..  M         MMM                  MM   MMM                 MM  M   ..                                                \r\n" +
"                                                       MM               M                                       MMM.......MM                                       MM               M..   M      MMM                       MM MMM                   MMM    ..         MMM                                   \r\n" +
"                                                        MM              MM                                      MM       MM                                        M                MMM    MMMMMMM                         MM  M                           ..        MM MMM MMMMMM                          \r\n" +
"                                                         MM              MM                                     MM        M                                       MM                  MMM                                   MMM                             ..      MM   MMM      MM                        \r\n" +
"                                                          MM              MM                                  MM           M                                       M                    MM                                    M                          MMMM....... M   MMM       MM                       \r\n" +
"                                                           M                 MM                              MM            MMM                                     MM                    MMMMMMMMMM                                                      M  MM.........M             MMM                    \r\n" +
"                                                            MM                  MM                          M                MM                                 MMMMM                            MM                                    MMMMM           MM    MM       ..MMMM           M                    \r\n" +
"                                                             MM                  M                          M                 MMM                              MM    MM                          MM                                  MMM   MM         MM     MM       ..   MMM          MM                  \r\n" +
"                                                              MM                   MM                      MM                   MM                          MM          MM                      MM                                     M       MM   MM       MM       ...   MM           MM                 \r\n" +
"                                                               MMM                  MM                     MM                     MM   MMMMMMMMMMM         MM            MMM                    M                                       MM       MM MM        M   MMM ...   M             M                 \r\n" +
"                                                                  MMM                MM                     M                       MMM          MMMM       MM              MMM               MM                                          MM       M          MMMMMMM .. .. MMMM     MM    MM               \r\n" +
"                                                                     MMM             MM                   MM                                          M     M                  MM            MM                                            MM      MM       MM M  MMM ..  ..    MMMMM  MMM MM               \r\n" +
"                                                                     M MM             MM                  M                                           MMMMMMM                  MM           MM                                              M      MMM      MMMM   M  ..   ..            MMM                \r\n" +
"                                                                     M  MM MMMMMM       M               MMM                                          MM                       M            M                                                M      MM            MM   ..   ..                               \r\n" +
"                                                                     M   MMM  MMMM      MM           MMMM                                           MM                        M           M                                                 MM        MMM   MMM   M   ..    ..                              \r\n" +
"                                                                     M             MMMM  MM      MMM                                                MM                      MM         MMM                                                    MM    MM    MM MM    MM ..     ..MMMMMMM    MMM               \r\n" +
"                                                                     M               MM  MM     MM                                                    MM                    M         MMM                                                       MM    MM      MMM MMM ..     MM     MM    M M               \r\n" +
"                                                                     M               MMMMMM      M                                                     MMM                 M         MM ..                                                       MMM  M MMMMMMM..     ..    MM      M     M MM              \r\n" +
"                                                                     M                  MM      MM                                                       MMMMMM            M        MM  ..                                                          MMMMM       ..    MMMMMM        MMM   M   MM            \r\n" +
"                                                                     M                  MM      M                                                        M     M           M         MM  ..                                                            MMMMMM    ..    M   M         MMMMM    MM            \r\n" +
"                                                                     M                   MM   MM                                                         M     MMM         MMM       MM  ..                                                                       ..MMM     M                  M            \r\n" +
"                                                                     M                     MM MM                                                         M        MMM     M   MM      MM  ..                                                                       MM      MM                   M           \r\n" +
"                                                                     M                     MMMM                                                          M          MM     M   MM   MMMM  ..                                                                     MM         M                   MMM         \r\n" +
"                                                                     M                     MM                                                             M          MMMMMMM   MM MM   M  ..          M                                                      MMM            M                      M        \r\n" +
"                                                                     M                 MMMMM                                                              MM                   MM MM   M  ..        MMM                                                     MM              MM                      MM      \r\n" +
"                                                                    MM                  MM                                                               M                     MM M    M   ..      M  MM                                                  MM                MM                       MM     \r\n" +
"                                                                    M                  MM                                                                M                       M     M   ..   MMM   MMM                                                 M                 MM                        M     \r\n" +
"                                                                    M                MMM                                                                MM                            MM   .. MMM     M                                                  MM                 MM                         M    \r\n" +
"                                                                   MM             MMM                                                                   MM                          MM   ...MM        M                                                  MM                  MMMMMMMMMMMMM              M   \r\n" +
"                                                                    M            MM                                                                      M                        MMM  ....  M       MM                                                  M                               M               M  \r\n" +
"                                                                   MM            M                                                                       MM                       MM ....   MM      MM                                                   M                               M               M, \r\n" +
"                                                                    MM           M                                                                        MM                     M M...     MM      MM                                                   MM                              M               M, \r\n" +
"                                                                     M          M                                                                           M                     M         MM      MM                                                    MM                             M              MM,,\r\n" +
"                                                                    M          MM                                                                           M                    MM       MMM      M                                                       M                             M              M,, \r\n" +
"                                                                    M          M                                                                            M                   MM        M        M                                                       MM                 M          M             MM,, \r\n" +
"                                                                    M          MM                                                                           M                  MM        MM       MM                                                        M            MMMMM  MM    M  M            MM,,  \r\n" +
"                                                                     M         MM                                                                            M                 MM          MM    MM                                                         M            MM       MM MM  M            M,,   \r\n" +
"                                                                     M        MM                                                                             MM                MM          MM   MM                                                          M      MMMMMMM          MMM  M           M,,    \r\n" +
"                                                                     M        M                                                                                M              M              MMM                                                            M   MM                     M  M         MM,,    \r\n" +
"                                                                     M        M                                                                                M              M                                                                              MMMM                      M  M         MM,,    \r\n" +
"                                                                      MM       MM                                                                               MM          MM                                                                                                         MM M      MMM,,      \r\n" +
"                                                                         MM     MM                                                                              MM       MMM                                                                                                            MMMMMM MM,,         \r\n" +
"                                                                          MM     MMM                                                                            MM  MMMMM                                                                                                                     MM,           \r\n" +
"                                                                            MM       MM                                                                          MM                                                                                                                                         \r\n" +
"                                                                              MMMM   MM                                                                                                                                                                                                                     \r\n" +
"                                                                                  MMM                                                                                                                                                                                                                       \r\n";
	for (int i = 0; i < map.length(); i++)
		if (i % 302 > 150)
			System.out.print(map.substring(i,i+1));
	}
}